# local dev environment:
# theme: minimal-mistakes-jekyll
# Using remote_theme for github pages:
remote_theme: "mmistakes/minimal-mistakes"

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OscarWang114
email: chihhaowang.oscar@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    My blog.
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://oscarwang114.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: OscarWang114
github_username:  OscarWang114

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Minimal mistakes configurations.
# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/

include: ["_pages"]

locale: "en-US"
name: "Oscar Wang"

paginate: 5 # amount of posts to show
paginate_path: /page:num/

comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

# lunr search by default, consider using algolia
# Only the first 50 words of a post or page’s body content is added to the Lunr search index.
search: true

author:
  name   : "Oscar Wang"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Loves programming, idea sharing, and running. Embraces language and culture diversity."
  email  : # optional
  uri    : "https://oscarwang114.me"
  home   : # null (default), "absolute or relative url to link to author home"
  github           : "OscarWang114"
  linkedin         : "oscarwang114"
  facebook         : "haohaowang.oscar"
  twitter          : "OscarWang114"
